name: CI for a Rust project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: stamp-runner
    name: Lint (clippy & fmt)
    steps:
    - name: Lint
      run: cargo clippy --verbose
    - name: Format
      run: cargo fmt -- --check

  build-and-test:
    runs-on: stamp-runner
    name: Build and Test
    steps:
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Attestation
      run: $ATTESTATION_HOOK target/debug/executable
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: artifacts
        path: |
          target/debug/executable
          target/debug/executable.cert
