name: Project Rust Small

on:
  workflow_dispatch

jobs:
  run:
    runs-on: self-hosted
    name: CI Build
    steps:
    - name: Fetch dependencies
      run: |
        source ~/.cargo/env
        /bin/bash "$LOG_HOOK" TIMESTAMP BUILD_START "$(date -Ins)"
        cargo fetch
        /bin/bash "$LOG_HOOK" TIMESTAMP POST_CONFIGURE "$(date -Ins)"
      working-directory: ./project_rust_small

    - name: Build release
      run: |
        source ~/.cargo/env
        cargo build --release --offline -j4
        /bin/bash "$LOG_HOOK" TIMESTAMP POST_MAKE "$(date -Ins)"
      working-directory: ./project_rust_small

    - name: Run tests
      run: |
        source ~/.cargo/env
        # cargo test -j4
        /bin/bash "$LOG_HOOK" TIMESTAMP POST_MAKE_CHECK "$(date -Ins)"
        /bin/bash "$LOG_HOOK" TIMESTAMP BUILD_END "$(date -Ins)"
      working-directory: ./project_rust_small

    - name: Run attestation
      run: /bin/bash "$ATTESTATION_HOOK" "target/release/project_rust_small"
      working-directory: ./project_rust_small
